name: health_tizen
description: Tizen implementation of the health plugin.
homepage: https://github.com/flutter-tizen/plugins
version: 1.0.0

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: HealthTizenPlugin
        fileName: health_tizen_plugin.h

dependencies:
  enum_to_string: ^2.0.1

  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"